### ISSUE TITLE
Ajouter un test sur le nombre de joueurs

### ISSUE THREAD

**Issue by mathieu-maury** [HCarriere/tarot#2]
Le test n'est pas fait pour valider que le nombre de joueurs souhaité (3,4,5) correspond bien au nombre de joueurs sélectionnés. Ex: partie POEB1B
Il serait bien aussi qu'une fois le nombre désiré atteint, on ne puisse plus sélectionner de joueur existant ou en créer un nouveau. 
Merci !

**Comment by HCarriere** [comment]
Le test est ajouté côté serveur, et côté client les checkboxes se grisent désormais
